"""compteur de consommation des cles

Revision ID: 672b781b582c
Revises: f304233bcc68
Create Date: 2026-08-24 13:43:35.546447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672b781b582c'
down_revision: Union[str, Sequence[str], None] = 'f304233bcc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consommations_cles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifiant_cle', sa.String(length=32), nullable=False),
    sa.Column('jour', sa.String(length=10), nullable=False),
    sa.Column('analyses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant_cle', 'jour', name='uq_cle_jour')
    )
    with op.batch_alter_table('consommations_cles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consommations_cles_identifiant_cle'), ['identifiant_cle'], unique=False)
        batch_op.create_index(batch_op.f('ix_consommations_cles_jour'), ['jour'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consommations_cles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consommations_cles_jour'))
        batch_op.drop_index(batch_op.f('ix_consommations_cles_identifiant_cle'))

    op.drop_table('consommations_cles')
    # ### end Alembic commands ###
