"""Schéma initial de Lynceus (tables analyses, pages, domaines, signalements).

Générée à partir des modèles à la v0.2.0. Les instances antérieures, dont les tables
ont été créées par create_all(), sont estampillées à cette révision au démarrage sans
que la migration soit rejouée (cf. lynceus/migrations.py).

Revision ID: f304233bcc68
Revises: 
Create Date: 2026-08-24 11:09:56.233827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f304233bcc68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('carte', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('categorie', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('confiance', sa.Float(), nullable=False),
    sa.Column('modele', sa.String(length=120), nullable=False),
    sa.Column('fournisseur', sa.String(length=120), nullable=False),
    sa.Column('duree_ms', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'prompt_version', name='uq_contenu_prompt')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_content_hash'), ['content_hash'], unique=False)

    op.create_table('domaines',
    sa.Column('domaine', sa.String(length=255), nullable=False),
    sa.Column('nb_analyses', sa.Integer(), nullable=False),
    sa.Column('score_moyen', sa.Float(), nullable=False),
    sa.Column('distribution_grades', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('maj_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('domaine')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_normalisee', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('domaine', sa.String(length=255), nullable=False),
    sa.Column('analyse_courante_id', sa.Integer(), nullable=True),
    sa.Column('premiere_vue', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derniere_vue', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyse_courante_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_domaine'), ['domaine'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_url_hash'), ['url_hash'], unique=True)

    op.create_table('signalements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyse_id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=320), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('traite_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signalements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signalements_analyse_id'), ['analyse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signalements_statut'), ['statut'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signalements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signalements_statut'))
        batch_op.drop_index(batch_op.f('ix_signalements_analyse_id'))

    op.drop_table('signalements')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_url_hash'))
        batch_op.drop_index(batch_op.f('ix_pages_domaine'))

    op.drop_table('pages')
    op.drop_table('domaines')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_content_hash'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
